---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fortivpn-gateway
  namespace: flux-system
spec:
  interval: 10m
  provider: github
  ref:
    branch: main
  secretRef:
    name: buxfer-sync-github-app
  url: https://github.com/CalebSargeant/fortivpn-gateway
