apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:CV9scgqNbCwtd8coLZl/SLl+W/pmv1WwgwU87uYudsxv+stu/YU8YZG1hR1PomXYAOJyRetvupvMoSkY9mAlvKwSQqtV7AWrm+K0gZKiT4aNwxBoczODG1d8MP419v1JdhEcitTkG/bi4EUBeart1ACbE5099vOCkQwVLoA/5+ftM0f0y+DavcbJ7VJAeDXazlid6H4yU7KcHLLAHjXBQKYOvg3JdnLXxuFNn/ldBsJsX9VhQecTlLWxO/jsp2O/ICFrq7sNjYTwvEB4PtijNvROfhSogxMU5HyI3Wgz/94nJ76kcw+kl4aVKtkBQQLzkRVNSSUXVUQ=,iv:8qWc5cDOoRPxglM6nyhBpAFGV7pDHqsYhgkFtPW9nkU=,tag:UhtkHzrGIpO1ABnpteJk0w==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWd3pOdmtJZ0t0NVpYTXBn
            UHpxZVhCUXM2NDR5WUxzNEdpZnpRWUFWTFg4Cjc2OHh0ek5zRnZSd0VvZW1nbHM0
            aEZSU1hPM2RQNWszeVZhT0diZDg4cmcKLS0tIGpnZE9salBwNEhuazFuSjFLNVFR
            SGZ0NG1oK1JCSFhjU0VlOTZDZWMvSW8K/AtxcBZ+uh7TokWNQwaeU1Y/d1QwyQKk
            xeYHreYmpfq571DJp1gpR/thn2mXSV2Kgv/gSUYUglFXzcr+ZlLUaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-16T19:51:43Z"
    mac: ENC[AES256_GCM,data:YQ9T5KBH+FLxSW4Bag4Qn+Zy3yuvdCjq+t1ueFPZrtQ3KSZDM9kLRxOT4nPazj8VIghkunP4cehFbRcVva0P2aS+yBTzUXD0+rW4ZvVNxx0DhuFmzp/T/HrqOIhjmBaSHr4o1EZhNBiEsnA6wqh/6QaCXiDF4YnileML3RRTu7E=,iv:HYKRIbd/y78LxN9h5fHrpwg1/kxNZbb0lk6e4hViIhg=,tag:aNFt9IEiL+xcuPHFW0akIg==,type:str]
    version: 3.11.0
