# kics-scan disable=b9c83569-459b-4110-8f79-6305aa33cb37
# SOPS-encrypted Secret — stringData values are ciphertext managed by the age key pair.
# The "External secret storage is not in use" finding is a false positive; the values
# are encrypted at rest in this file and decrypted only by flux at apply time.
apiVersion: v1
kind: Secret
metadata:
    name: slack-bot-token
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:TvD3Ot77WzLBQ1drpSY9PaYleltt4nk9CEiPUSOB8KP0uWdI79I=,iv:wlbfL808+V/eNbMWnePD25Mvxog8bQA0TvYdkh0KM1w=,tag:6+iwzOKE4GsBj6ONb2EFhQ==,type:str]
    token: ENC[AES256_GCM,data:8Zt9KxMyKDK/YrvIWmEB2HvX15a1nx3pTxWtaeg7Zwl1BGcjaP7vJruukq+0DeL+3bkRtd7oW45y,iv:6EP1ZGbfkvVRLd9tKA/NRCxm4hBgDX0RnnUoyYf1w5Q=,tag:4IVLpgsnTvz++rWvSs4omg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTCt0SXhrOGQyalM0cVpx
            MjNxRlFmUS9LRU9jemU3WGdxT1UrMzAyM2d3Ckd2ZG1vS2ZUOTJRR3hrQzIwMHh6
            eTEwRlR0WXpzMEI3NUZkSTMrZ05QT1EKLS0tICtjM3MzTVh6bndEU2NSUk5QZyt5
            VzdqYmMvLzJadWZSUndIZmVzM0RQUm8K+xQRGGfPYpZ38zq70e1AG9DP3Ju9B1MR
            hFah3/VAQe/PIcqDQM3sUHAvf1qWYvbKF+/Iji6Im1FjCI2Q0Npd7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T10:33:41Z"
    mac: ENC[AES256_GCM,data:TQM38saNG4yerzhY3MdkwnT6XPSnKUPuZfB2rx/CvLMOJCi25WBHOCtVTvWuaIBLpOul1pOF5RF7V+MOu6VKXA2cJ/b0JoUC6C1Zahrj3K2NSb8ayfHqNMd26mseDlxjQp/ocSXJzopRMl+ZdFskGIooQP52hbmr8VDwh77yBjI=,iv:VBaafnLjHY0BqqTVk2wX3fFC8BX3wWhaIJdbn6lXXaE=,tag:sUOUPjOwcKaerGrjLreORQ==,type:str]
    version: 3.13.1
