apiVersion: v1
kind: Secret
metadata:
    name: n8n
    namespace: automation
type: Opaque
data:
    postgres-username: ENC[AES256_GCM,data:x9d9at6C17JvKdjwIfCKqg==,iv:X4C4t3cEhWZHmOJVJXnZT20X2L5FjFTjI2+kF4ZSeRk=,tag:fYDlgbYjwBAE38AVXAD2pQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:FAy/c5yKQ/qTE+EpzCPuhOvCbWuHpBaw,iv:gsnCyuQPbqN30+BhCvjiawxnoQOLclVxnZHpSOUGx7g=,tag:VGcaqJTNLA2TXTlFT4VFIQ==,type:str]
    encryption-key: ENC[AES256_GCM,data:FrB0d6HlgzjkwYLtxFYm7dvZjG72PJhy7WrVRpwMG4bqonWOLXzkdgDexiar5s2KdzpBMY96uQGYAKfKawY9ght4j46ks6i+SkvwU1ZVVnEqMsthb4eIMg==,iv:gQqX4jgW/1PYoZu7RvVlxHWJZkyoaFjp0k4eLBgS1Rg=,tag:Re8x29k3FbY/vI23EtjYdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZUzVKeFNMd3l4UlFvcjJ2
            QlNWMFdROWZNS3ppVjkwd3JIekhyNVVlL3dZCktvWllBWEFMc3Q3dURleS9wcFhH
            ODRxSzU0K3l3YktYNjRHdWVmV0VSemcKLS0tIFY3R0h0ay8yemRrVjBzZDE5eW1L
            SCszZ21EVjNQMk9WZFI4SWJCckxnTHMKwSxMnCeZYb6rGVEgT2SxbWY9EkIiT5pq
            NxEbfwJO9Ll/hCc+upYiQDSb6eldf/mrdOhGQpnfGACJQ1jPkp9lBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsem1idngyUCtSS3o1QSs5
            clgwRjZqUCtKeFhoZDZuTkFCY0gvQXFUUlZvCmUyQWxLYUZxU2o4MzRmd3hTeDh4
            b1BqRUZNejFBN3l4TnlXVEZPdC8rWkUKLS0tIHlkaU1welhjS0IzNFVXd1A1bDAx
            bnduQ3Z5U0t2eFNReXRnUHlBV2NMbHMK+PV7/5G8YrJrKuj40rwi9hVNjCkEZvcI
            DoCwrUEeXNtI1P0ENgs2U/6hnlj5O3L6vbFIttNZ6Earm+s+INJluA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-02-08T20:30:30Z"
    mac: ENC[AES256_GCM,data:uhPdRo/ItYV1kJzZ6E3Nr44MOxbePixTU+WbqTcZYhtNraINKzzCbNI3vjeIL+xTB520AlSJSDB3fuo3rplQC0ihwmWcJ15cY5WPPhuqFIa2To3Ojo85U85d8lc+/c9ZpO1v/nvrbGWPoGNEAa5AWwQlFKyNbufcUV+l6tgtcJk=,iv:H0tKDmreab3Ynf30PyWacZoTPqXXRVYoupd0eNBuEw4=,tag:Zgq5fzlBtygZsGBRh4mLUA==,type:str]
    version: 3.11.0
