version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /dockerfiles/n8n
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /dockerfiles/openfortivpn
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /dockerfiles/hermes
    schedule:
      interval: daily
    cooldown:
      default-days: 7
  - package-ecosystem: terraform
    directory: /terraform/gcp/prod/europe-west4/project
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform/oci/modules/edge
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform/oci/modules/network
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform/oci/modules/policy
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform/oci/modules/server
    schedule:
      interval: daily
