apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-emails
    namespace: misc
type: Opaque
stringData:
    emails.txt: ENC[AES256_GCM,data:VSA9FvnYoQkQyIVxqO8gKfwCGJjr,iv:LhW3w1sILv/Rw7nwMFl6hLu7h2uRFIbcjdBIcvPUg68=,tag:87xY8FxINHZPSekup+AwfQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpa0VyUlNBZ0xuSUNObUFP
            aGlNalE5b2d6NUZyYXkwc1V1VVFyVVh4RVM0CnhtMlcrNzBybVdrcE5KZk9YNnNR
            TG9kL3NTeHZRY1daVHY1d2ZwVkdSUDgKLS0tIEVMRDFlY3RvMTlXSlBydUZCQ0FY
            QVZvYlJ0UldLM2JycXRBbktIbEZjSHMK55KDuQqCN6G4MLOQCe7gHsqMQMD7aOPC
            9EJL2dbs9Zel37O1J4cMqZmrGlQS6+2oTfyTtQFXhQ2Agfcr+4gZrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuY1F0a1hQWEJJUEhhSGlG
            dGxucHFHQ3hrTVZ2cm4vSTVUT0R3SVlRUGkwCmlLRHZFSmNkWUFNb2hYMHNEMThr
            ZVc4dWp3dlc0Q094S0FraGo1bEN6bkEKLS0tIGhxVVR6SEJUS01qdnJqRTZ4bVJ1
            WmUyQkJyaEVML2JlYVZ1SlhqQ1o3MEkK+CPX0Im8ocgd1Eege/KT82CzXyzIpfEW
            8TOMtw7HQ79ND78J5SPAbgSdPAAjaQLxRNMAVqreFXp2Ik9KLa2t0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-20T20:43:35Z"
    mac: ENC[AES256_GCM,data:Gpg3zV7Rf9IKblQ91dYgpVVDIfJclj//4YFar6usKPyJhKIzGsWWWC3JQwvjBSsnRMjFjUUO5hWhVxtqt0A5nx5PboCxPFWPY62dlNyGtAc5mlxP4uQWofDDV//myZQSY81LHjUqFd9oiBLqmj2GOSatR0voiUJAeQEN0mRTwHo=,iv:dQjpf/Zb/pBI1y962zkm/xWQKyWRV2KofdxCWR+F380=,tag:41PL3R6MQ4MonqT1DueYQQ==,type:str]
    version: 3.11.0
