apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    dns-cloudflare-api-token: ENC[AES256_GCM,data:eS50zFpxvvg7Vebpw2+EYd7naE/uQQ2ba/eMKWcIURdoD2BubLmV+v9s7g2KlGp5cvb+8gN5Ro0=,iv:M/v7lAyq/7TOrGnljCyPAYIPjOWjBB+QZZj2ZnkKOPE=,tag:h2rMikpibFLNHH1wRew3zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrLzIvUEZuVjAyZXVkU0Qr
            SEl5b1BUbFNxOWZwZHVEWUFoTnZNeWtSaWtnCjR6Vk81MkxpSjJmTzQwWmRSU3k0
            KytmRytLVEFzelZyWktCRUQ1TzVFMEEKLS0tIHBMUjhGWlhXNkhwclhpM1ZPR1pk
            RGRWUmxWakM3QWc1WTZheWgrL1pVRTQKRsvvhyzDFzm2Avnyv20MwKUz0gEz8zhS
            7WQ9PRb3pjsiV8kAq1MTwzLWuXvKVhOFP9ELGFdBl0g84pVsrEf4uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1TWU2NkhkRFBMOHlmOGFW
            b2FMd094d1NyN2c5aVJKQVpMTVIrYWVQQjFnCkdBaXFQYkt4QWFMdWUrSzZKelV6
            M1JvWk1mMDQ5d0k0WC9nQVZBeGVwdDAKLS0tIEpuWEVMSWt5WDNqSkJQczY4N2tJ
            UlBNc214WERpeDJJQnFhUVAzMnI3cW8K+6oAiK6S7ocATrW55uF11dQLmlMAd+Zq
            2S1D3WAn+AuhltMeQqZ/2ku3U22GcmbayiHpZ9ufP5SahEzXTpLpWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2024-12-09T19:39:25Z"
    mac: ENC[AES256_GCM,data:Ms08RzWTd/LezSt22Pw8rdraAJ8EJYfbEWUhrEC5nR2djf5ieBJkhqXtj/Wasi7TjbQYPaHpFbCftkyQU3+afZUySurng+yxP6Qeh5qY3JtTREHxb+F0UZYU1oha/XRqICPOSZULcNK28pWfyi/MLWjSNGcPdbBmCVkAcBy7164=,iv:tA+53KX3q5kxlcEXbMbhlnkJtYUW02ZTAayqmCEkdJc=,tag:OQDAyeCby6sgiagYOaMYRQ==,type:str]
    version: 3.9.2
