apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: media
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:Hxn9EDhhm03V7vbonOAWQFElEweq23CWg+jWBjwUoOQ=,iv:X0zB1eKEnXr0vQEVALsOmbZm3gqgODYaaDZRmvjHNqE=,tag:zbojGS24mV0a+7KYMN3+xw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:srrLnmSHqdP2HTk2iFfMN+4h0HOrr4r8yLnFmAMpGy8=,iv:7KHL3TD1eaKpUR2d0p3jguEN0TvERFLZMLOabit9wOs=,tag:RtUEzg2LopqQTvt2K9dAFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdlVYZS9lS0dVZno0K21Y
            YnZGZzl5Z0kxd25scHNoSXRNeStTSEpxMkg0ClRIc0FnSkNDZGdFL1BhRlJaMHA1
            aXJNbzhhU3kzTlZlUG82ckNtdDE2U2cKLS0tIFJUSW5xa2N0K1pJTHZFb1ZqMHVq
            cVIzSGZUdEQyVFh2UzFNcTRXRHlTREUKALVYZfid23kP6VIRBRh/RhPl4p+XdD6n
            yPSho4SRN/nxpucm4YuHo6aYYO0Ec87ntV7RHwRksKUxctHf1ZQWNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T08:16:46Z"
    mac: ENC[AES256_GCM,data:HbB+Chs/XD8l5GOIij2xJwp7sTqfdki3UTdScTr91/G19h2dDZocQwenCCc0/Ijgfl3MEvH20ADHoG8ynyqP+G5C/1QwlHDiEjA2pYK9ca31vYNk8VchRkykc2n1OMBhzj9aq8wVD6kW3LEZAazVQIa3ZHzOVnfJp7G5iSzalkk=,iv:YQIH1eF9Xs5W8HodQEn2i6TS05+8Yqlvrz/STrVK4Ig=,tag:vIrIuR7Oc4eTXrUVBZOHlw==,type:str]
    version: 3.11.0
