apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: media
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:Hxn9EDhhm03V7vbonOAWQFElEweq23CWg+jWBjwUoOQ=,iv:X0zB1eKEnXr0vQEVALsOmbZm3gqgODYaaDZRmvjHNqE=,tag:zbojGS24mV0a+7KYMN3+xw==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:srrLnmSHqdP2HTk2iFfMN+4h0HOrr4r8yLnFmAMpGy8=,iv:7KHL3TD1eaKpUR2d0p3jguEN0TvERFLZMLOabit9wOs=,tag:RtUEzg2LopqQTvt2K9dAFQ==,type:str]
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWVJCZmpJRWVGdWgwWkpn
            VWE3TGQ1cmRtcUxYTFJpL2JaNkJFZlRmVkFFCnVqT3hSTDJxcDA3enhWUytORXVa
            RXBqVmo1elpDbVNiU2ZQdDRmS1hUeFEKLS0tIE9CQ0RYQmszdURRMjlNOHM0cjhS
            d08zTGdLSEladk53NjBVSDhjbVRncUkKiKpQHxw8li8nYuVAKxerJE9FeHTyAAtW
            RYvrYIaqksOKvw8s4v80337e5Rm8HBbo77rx6pN3B6lGAcI0+SrQNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T08:16:46Z"
    mac: ENC[AES256_GCM,data:HbB+Chs/XD8l5GOIij2xJwp7sTqfdki3UTdScTr91/G19h2dDZocQwenCCc0/Ijgfl3MEvH20ADHoG8ynyqP+G5C/1QwlHDiEjA2pYK9ca31vYNk8VchRkykc2n1OMBhzj9aq8wVD6kW3LEZAazVQIa3ZHzOVnfJp7G5iSzalkk=,iv:YQIH1eF9Xs5W8HodQEn2i6TS05+8Yqlvrz/STrVK4Ig=,tag:vIrIuR7Oc4eTXrUVBZOHlw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
