apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ysz4Ru9A6BlZgY7XrJr5FOs/kiUUT5S2khXS9w==,iv:zMiArXjQ5xaHKrKzRGaGibXpMR0bZ7LCYtAbHytTWP8=,tag:2GWw+YDavzCey0fPZLSKUQ==,type:str]
    username: ENC[AES256_GCM,data:y3jKrlJcOXK9iHUi7icQ7Q==,iv:DaxVg0Ez67Wib9hXsrN37rCgD3rzHNWnjQhK/e9DA3k=,tag:zOTtT/vF0qvgWHk/Us7PAg==,type:str]
kind: Secret
metadata:
    name: privado-vpn-credentials
    namespace: vpn-gateway
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdnBpUnFoMmlVU0lWME8r
            R2xrT3hwdlNwNUZQOXBHRXhDQm1ZRkNkUFdjClVnRVdNVlc0a2RFdDJmeUplZnFQ
            Y0hzSWdYVFpyODlSNEJmR3pBbXR2ZWMKLS0tICtURSt1VDQ5ZitaZDQxQjhOQ0sz
            MlRKVGdmMEp5d05DaUtlZk5rMzl0ZjAK8EiVDJu+St5NUaDTlE6b0WneSbn0fQAe
            mYU+Z9qQnC9FQgwtV4e1SMCJmLZlprO9JW816EVePP2Z6+j9kbkJEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T22:01:15Z"
    mac: ENC[AES256_GCM,data:GDI4lb+eL+03Lqj92yadvZRA+y321H2By2WYQDIYZl0X7OXaZJNTAebi126GRkChDQ5izE0IeSBlYEN4cHW0eWnMNZt00JL66qFr8pzxYNq5JGKvBlLRSHwzL4jgAGOB+zBBeOp5T7n5cVo/VUgowKJn32HegD9I/mGYa5tm6WQ=,iv:Ok6IzWpU1CGRfP8VsjKkYIngPYn/qXvCwMqNx2XpwNM=,tag:xVG1lk+AeHrzxwbkpZY/8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
