apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ysz4Ru9A6BlZgY7XrJr5FOs/kiUUT5S2khXS9w==,iv:zMiArXjQ5xaHKrKzRGaGibXpMR0bZ7LCYtAbHytTWP8=,tag:2GWw+YDavzCey0fPZLSKUQ==,type:str]
    username: ENC[AES256_GCM,data:y3jKrlJcOXK9iHUi7icQ7Q==,iv:DaxVg0Ez67Wib9hXsrN37rCgD3rzHNWnjQhK/e9DA3k=,tag:zOTtT/vF0qvgWHk/Us7PAg==,type:str]
kind: Secret
metadata:
    name: privado-vpn-credentials
    namespace: vpn-gateway
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2S29Ia2JRVC85WHlUbFh5
            M2o4SXoreHlxNG0rMERFUjgxZVlnNEV3aG5vCjZucEhZR3pOTXVZU3JLajIzNi9h
            dzE4YURoTzBjZUNhczVxVGlTVE9uNEUKLS0tIGltQWErTHZPUUFkV1EzQ2daS3o0
            c3hGelgxNGNjSVdKSmtZSFRXUlBpVnMKcJICbSByPJWk/YqjdEfeVXMC547avwgl
            0W6RHR5Is9BxeAXZLUGHUY31PON5QnHZdVDpcgllPhCimH4f//nC2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ2ZHODJMbVFWMG1mZFNP
            cVQ0YjBaQjRFYmZwcS9hYjIzdWFra21aK0ZjCngyY2cwVnVubElUZG1vVG9XT2w1
            MkhXSWVsaVhJcmVpN05JdjFkN21Yc28KLS0tIHpsUGhlMlNmODdwTUF6UFVqYW5R
            cWU0S0lVenJXMEhCL1JoaGhoNkRHZUUKUi6H7V3eRfWFS3zepr0SkO9N5f9MpZmd
            t/NT2MUVBm+x9uU3jcKrqrXQJLPDlRblhP034qnjaWRHX1JRQwgUZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T22:01:15Z"
    mac: ENC[AES256_GCM,data:GDI4lb+eL+03Lqj92yadvZRA+y321H2By2WYQDIYZl0X7OXaZJNTAebi126GRkChDQ5izE0IeSBlYEN4cHW0eWnMNZt00JL66qFr8pzxYNq5JGKvBlLRSHwzL4jgAGOB+zBBeOp5T7n5cVo/VUgowKJn32HegD9I/mGYa5tm6WQ=,iv:Ok6IzWpU1CGRfP8VsjKkYIngPYn/qXvCwMqNx2XpwNM=,tag:xVG1lk+AeHrzxwbkpZY/8w==,type:str]
    version: 3.11.0
