apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ysz4Ru9A6BlZgY7XrJr5FOs/kiUUT5S2khXS9w==,iv:zMiArXjQ5xaHKrKzRGaGibXpMR0bZ7LCYtAbHytTWP8=,tag:2GWw+YDavzCey0fPZLSKUQ==,type:str]
    username: ENC[AES256_GCM,data:y3jKrlJcOXK9iHUi7icQ7Q==,iv:DaxVg0Ez67Wib9hXsrN37rCgD3rzHNWnjQhK/e9DA3k=,tag:zOTtT/vF0qvgWHk/Us7PAg==,type:str]
kind: Secret
metadata:
    name: privado-vpn-credentials
    namespace: vpn-gateway
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NXFLOGlaM1hoRURsL2Nj
            RzQ4RTI3Nm9nWmI4MVozQlFvL3drejV5a1U4CnVaM1Q5T080WWdVWWJxQllPZm9l
            QnlRZ1Jjdm9ucFB0UTUvc3lRUFVZZncKLS0tIEUxSzNFSTRBY0VaREY0L1FtakVT
            dGFsOFNVdnpNVFBrZW5mTCsvY2sxejgKQSDdip5qNipc3l/Tw8nRywDCMWES9WhW
            4oh+x79e6Pw+gX2DAaHJgf2+3zQUbvTAWoll5v2Kbly3oygle24k+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T22:01:15Z"
    mac: ENC[AES256_GCM,data:GDI4lb+eL+03Lqj92yadvZRA+y321H2By2WYQDIYZl0X7OXaZJNTAebi126GRkChDQ5izE0IeSBlYEN4cHW0eWnMNZt00JL66qFr8pzxYNq5JGKvBlLRSHwzL4jgAGOB+zBBeOp5T7n5cVo/VUgowKJn32HegD9I/mGYa5tm6WQ=,iv:Ok6IzWpU1CGRfP8VsjKkYIngPYn/qXvCwMqNx2XpwNM=,tag:xVG1lk+AeHrzxwbkpZY/8w==,type:str]
    version: 3.11.0
