locals {
  terraform_version = "1.11.3"
  hcloud_version    = "1.50.0"
  aws_version       = "5.82.2"
  routeros_version  = "1.74.0"
  sops_version      = "1.1.1"
  oci_version       = "8.0.0"

  region_vars      = read_terragrunt_config("${find_in_parent_folders("region.hcl")}")
  environment_vars = read_terragrunt_config("${find_in_parent_folders("environment.hcl")}")
  provider_vars    = read_terragrunt_config("${find_in_parent_folders("provider.hcl")}")

  company     = "sargeant"
  provider    = local.provider_vars.inputs.provider
  region      = local.region_vars.locals.region
  environment = local.environment_vars.locals.environment

  # Which OCI TENANCY a leaf belongs to, expressed as the prefix of the four env
  # vars that carry its API credentials. `find_in_parent_folders("provider.hcl")`
  # resolves to the NEAREST one, so a subtree can shadow the default simply by
  # having its own provider.hcl — that is how a second tenancy lives in this repo
  # without every leaf sharing one credential set.
  #
  # Defaults to "OCI" so terraform/oci/provider.hcl (and every leaf under it)
  # keeps reading OCI_TENANCY_OCID / OCI_USER_OCID / OCI_FINGERPRINT /
  # OCI_PRIVATE_KEY_PATH exactly as before — this change is a no-op for them.
  oci_env_prefix = try(local.provider_vars.locals.env_prefix, "OCI")

  oci_tenancy_ocid     = get_env("${local.oci_env_prefix}_TENANCY_OCID", "")
  oci_user_ocid        = get_env("${local.oci_env_prefix}_USER_OCID", "")
  oci_private_key_path = get_env("${local.oci_env_prefix}_PRIVATE_KEY_PATH", "")
  oci_fingerprint      = get_env("${local.oci_env_prefix}_FINGERPRINT", "")
  # The OCI half of the generated provider.tf. Suppressed for aws leaves ONLY: a module may
  # declare `required_providers` exactly once, and this generate block owns that declaration,
  # so an AWS module carrying its own versions.tf would collide with it. Keyed on `== "aws"`
  # rather than `== "oci"` so every pre-existing leaf renders byte-identically and nothing
  # already applied sees a diff.
  oci_provider = local.provider == "aws" ? "" : trimsuffix(<<-OCIEOF
terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "${local.oci_version}"
    }
  }
}

# Credentials come from the ${local.oci_env_prefix}_* env vars — see the oci_env_prefix
# local above. Region comes from the leaf's region.hcl rather than an env var, so a second
# tenancy in a different region cannot pick up the wrong one from the ambient environment.
provider "oci" {
  tenancy_ocid     = "${local.oci_tenancy_ocid}"
  user_ocid        = "${local.oci_user_ocid}"
  private_key_path = "${local.oci_private_key_path}"
  fingerprint      = "${local.oci_fingerprint}"
  region           = "${local.region}"
}
  OCIEOF
  , "\n")
}

inputs = merge(
  local.region_vars.locals,
  local.environment_vars.locals,
  local.provider_vars.locals,
  {
    company      = local.company
    domain       = "sargeant.co"
    sops_path    = "${get_repo_root()}/sops"
    ansible_path = "${get_repo_root()}/ansible"
  }
)

remote_state {
  backend = "gcs"
  config = {
    bucket = "${local.company}-${local.environment}-terraform-state"
    # path_relative_to_include() returns OS-native separators; on Windows that
    # yields backslashes, which become a DIFFERENT GCS object prefix than the
    # forward-slash prefix used on Mac/Linux/Atlantis — silently splitting state
    # into an empty parallel tree (every resource shows as "to create"). Force
    # forward slashes so state is identical across platforms. No-op on *nix.
    prefix   = replace(path_relative_to_include(), "\\", "/")
    project  = "magmamoose-terraform"
    location = "europe-west4"
  }
}

generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  backend "gcs" {}
}
EOF
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
# Provider configuration generated by Terragrunt
provider "google" {
  project         = "magmamoose-terraform"
  region          = "europe-west4"
  impersonate_service_account = "deployer@magmamoose-terraform.iam.gserviceaccount.com"
}
${local.oci_provider}
EOF
}
