locals {
  terraform_version = "1.11.3"
  hcloud_version    = "1.50.0"
  aws_version       = "5.82.2"
  routeros_version  = "1.74.0"
  sops_version      = "1.1.1"
  oci_version       = "8.0.0"

  region_vars      = read_terragrunt_config("${find_in_parent_folders("region.hcl")}")
  environment_vars = read_terragrunt_config("${find_in_parent_folders("environment.hcl")}")
  provider_vars    = read_terragrunt_config("${find_in_parent_folders("provider.hcl")}")

  company     = "sargeant"
  provider    = local.provider_vars.inputs.provider
  region      = local.region_vars.locals.region
  environment = local.environment_vars.locals.environment
}

inputs = merge(
  local.region_vars.locals,
  local.environment_vars.locals,
  local.provider_vars.locals,
  {
    company      = local.company
    domain       = "sargeant.co"
    sops_path    = "${get_repo_root()}/sops"
    ansible_path = "${get_repo_root()}/ansible"
  }
)

remote_state {
  backend = "gcs"
  config = {
    bucket = "${local.company}-${local.environment}-terraform-state"
    # path_relative_to_include() returns OS-native separators; on Windows that
    # yields backslashes, which become a DIFFERENT GCS object prefix than the
    # forward-slash prefix used on Mac/Linux/Atlantis — silently splitting state
    # into an empty parallel tree (every resource shows as "to create"). Force
    # forward slashes so state is identical across platforms. No-op on *nix.
    prefix   = replace(path_relative_to_include(), "\\", "/")
    project  = "magmamoose-terraform"
    location = "europe-west4"
  }
}

generate "backend" {
  path      = "backend.tf"
  if_exists = "overwrite"
  contents  = <<EOF
terraform {
  backend "gcs" {}
}
EOF
}

generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite"
  contents  = <<EOF
# Provider configuration generated by Terragrunt
provider "google" {
  project         = "magmamoose-terraform"
  region          = "europe-west4"
  impersonate_service_account = "deployer@magmamoose-terraform.iam.gserviceaccount.com"
}

terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "${local.oci_version}"
    }
  }
}

provider "oci" {
  tenancy_ocid     = "${get_env("OCI_TENANCY_OCID", "")}"
  user_ocid        = "${get_env("OCI_USER_OCID", "")}"
  private_key_path = "${get_env("OCI_PRIVATE_KEY_PATH", "")}"
  fingerprint      = "${get_env("OCI_FINGERPRINT", "")}"
  region           = "${get_env("OCI_REGION", "ap-sydney-1")}"
}
EOF
}
