apiVersion: v1
kind: Secret
metadata:
    name: onepassword-credentials
    namespace: general-system
stringData:
    1password-credentials.json: ENC[AES256_GCM,data:qyqwVVYwFoRZyMBt+zSOSZBKcgIy8ufcMJJFJqoxQuuWvV0NnTT7pYPzyPX+uiH+L7YUGSo3BrmiGpP0gfJzjDgmzmddaAdUI28O4soepnMvflCbnCXhTePwgnljNrI69tM0YWD7OXu18Wo6HvmU8mPsEqNnNZ2emoa4GllvWM9IAnBg8DI9X1sgzSzM5UZ2PzXSTQm7+2u6KGfbIy8QjoomnssfRXJjRfex6AVLW9I4gUQFLMcKvGsmbyE3HmS7P9IoF5WU/TRFHrg5GYFZ9fLttBNskndE05KgEWsx1SS/PJqIXJ9ufgDsZJyWKrbjQ+gk+9mNp+AEGWzly0C7y6H/xNfpd5aI4WUTR8uUx/ISWiD/tw6TUEsjMhstOqizSrD1ycHnV6vKvGI32ahkpKZ78G1u0kJbnRJldzvuwN7Z7KTX61uY/ABcLtvbeSoaiZkVxRvrOXpGZR3AuY7LPYH//oTxCnOzIrvx6Qrs3E9MUpNHi2s8RLwHAKKy9lPzQ+Pft7+9HSCRi/wRvy9/mRCaqgxPPYfm1BhgYXQFpoi+TOzBOIjpR2G9JLAPok9q2wtGGDPUbWos9lY4yCCLuDGLJm+tl7VOp1UHierBhuegmdZGTCuw17wt1SehyRqOE/BOyGdnq6MlbXV0m3Sz9gRysmmRXcrS5D+3mNzdz0Uw4Mi826KDtVZeV+0Muw8PxrKBVPSOK+OMVU92h7ZjFSQ/0EQK1MnKknvFEV5cKxo0uTpRR1wSl30wfXH+EbTMBCTvOYSDEFd/rcLBHXAZ4x4kxRov0ZdcwimYOpGMzmlD5s7Q9c4qkyrsStRGhJ14g1AZU5g2fpFzsOpi/WvNI0WejMzwOcs96zRa0u56OfKzRjhNyEjgm6b+7YUVkJsywRasWtWoR5ttzNVHgBCn3QcXHT0ElWeXw4vmhc+gxEj5qS6i99I/Lp1gG6PFuJi6Nt6XwoCINSMeHiTjm9m+r9fKzIXt08cXOWeq1tzM65evZmmV91QsNHo3LkvzeFT1WnJvS7w00fM7O95dQQGKTn9KhRWQU2IRqltb3VfEl74D+MLLnE15HO3fehrE3oSj3Ysvj5K06pg5GeK3Zsx1mlvGXFpwAtS91JqCM3a1dDLoRHJA3b5Kax5XNZO1v3N6IIOFbLp4e8lkQwVgIxb5YGKg3mBwJbYK6qAPQ7hKShke5x/aMtPMxhnPpHNz8qfYastpJ7BvXDL/fcih4rrur8ZXFZhILhlZSRhPrHTkAYVlgHF7R0FFHcF/2DpnWJmq7Vg5VfgRZGsTMtdFBnpwnrmlwxfBWc2hotcuFzes4+/Ciu+AVfomnpR4cVloHcYb1lpmOsMbx656g8Hvsm6wWQRps6E8ygLqftYlPFqV2q+z2bqZDDdTn5sLCU9hRqD+AOTtDsf9eYa7SawnWgzqeyaVTMVq1rQ58pufNftIvaCg8qs4856K6Ry8xprf2lGu55RFb25euS6lvBbTBTevTfj7HCw9r+wWtzh5T1/fc2blqpgKhAEY7ItsPVBXqDnHlYIOyY30ENSaI1sCRLCbKG8Kg09W8tRgBMbBIZHyj2evgqDwNHFdjb8BDKXgX88qAvthhBvEEqT1ui6n3fO2JgzTmQ2FQO3XLAeAFFWBVsdz+2zTk4KRGDlCDcCH/XoTnzgfztpi/TN3QvWUYZzLP9mZ3x4Wm5sGKRCKIlcqSmumYVIsYd7sTJBrQd7UQE+uw6IykQ7vqfjGW1OlHq5bbFvJAFnVYS6LAElWSpcyve+trUPJi31d8OijO9FkqoTHPUH8qv4hf85Iqrw3ULg6o5VoMqDkJN+6syzmrCUVUvPrr0zhTpScrbqAPBnF46ZK+pxLrn81SqUfgMzfzuVU11wJHgdZ9rVp7/FXIlgmujieNy+fIjgYm/xTgPrCaITfgfxxyYQt4zznqjI5,iv:xEAPblQ+Ag7CiBVpNLgDi4YkcpzOltspR01cbPEEAP0=,tag:KvQZrBC45tfi876aOwF0eg==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWkRZMDlHT2tKU3ExQVBN
            dUtlKzQ5VjFHNGk3L2NNanA0QnpUbDYyblJZCk0xTEFjOXFUUXpnSmd4cmVFUXFG
            Q3lSWmxxNFhBanhPMTFrREVtUFc2TjAKLS0tIDRvZnA5bVFjZzdxUXN4UnNOL3Vm
            TVN2amh1Z2dHRHdPcGFrZnh4d0dleGsKQylzzqH3N22aIszcfX6Mi74tDmOAKQ/w
            I1r2UxrsDAdnUDatuowtqh2USWNiwcIg9XyA8Y5uUbU8t255RxUfKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWXZUMUNYKzF6MHlleGJr
            bXh4cm92clNnckl3ZlBCQjk3WmlRd3FmeGk4Ck9ZMENzNGh0T0ZMaGpnVUpCOFVV
            eURzOUIzazkxeTJ5NGFISzBhRnlQNWMKLS0tIHFuemJHWFlQWmwwQXJiTEpzS3B2
            a1NOSTJ6eVI5a3lZWjRXYTFaUlVWTm8K/DDH41nL3ml+q8jXHUbB9/IcnkclzrUT
            wbEpB2EPxluLJ2N1t7GMNHnYe4Bv2ulF9i9ys4RHlnm5WSMUbfY6Tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T08:33:14Z"
    mac: ENC[AES256_GCM,data:2KO7gGZ1k/egqEH8mO9Jk2b3Zlu8uXV8mmjP2fmYUzftHE3g2bkF4SyR0hVMblJzdOJOMt2eEjhZgYRQFYEDi1MDtmcA1zoBccywOPY0dcX/O/1HAUHi2Gq6mSCI9FEmiuw3qDlwSjjoxWbP2z8CddZNIWo+6iHGVgcfbulDNaY=,iv:aorysJGOI1QdehN+F+kWdwB3F+AgeXOvyB6DlyczRgk=,tag:6YukuqfKQE9qYsuj/wDTyg==,type:str]
    version: 3.13.1
