apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: core
stringData:
    token: ENC[AES256_GCM,data:dD6/zs7i5BwR/JildgjjjQNKSn+OrCl/BwqPHOTshOHwzUdmqD04N46rEIghWd+cVCx3qYFqdrJasNxQRBs4zPalg4VV/4kSEp2LFjnFiW7+PT1RdQTpHWuWTrekDcaoozORjZsCHOIDbCpJPbAOi5en0r075humQIyxlNvbRe/shInL/QhviWX5Xgffaa1AZpDN99igo4vYsSehqEGejAh7+cZrVvx8Av9R31V2L7PrQKxyE7aIe2onkaXwl6ehAcFNF3e9Ir+Uci70CosUweDneYrYC0fatbyCpsnODi7bAGS1dgmb4gmKZFwY3rCHMMNpAhVHq0hN9HJ2w4CgounYde0d5t9DO4Eja7BD/tv+g7g0eHt36WZISOZ8bvsBn+gj4qniZlXnoCMvNFcvhDR8VU4BBh1I66Co21vXuLAbCn00GOX4Cou+u50Tl9EnJ2Eg+sk6YgZ5OAUotCvdtKTtIMF3npUHnAypIwVa9QzH7LngtYwFVs+jzBl/pEhu1HUl957mND0IHyV2PbZXWQFOKus90J6J7yuILpWe2FGNSk+9csdLxVoj+CQRoZFEWcXq7ZU697gCAw1SNpXhorjT3FSZvuWdUBxA3o78tEAH4k1TYg212kfjQGzOXZ1uxblTN/l19mHz9Rbt8XN4gXs8fMpC1EgmHiSFElKuoO2gj9aze2xl0wbGPEgD3zxZ3ighu77NpqTxbvGxDsefCUH2ln8tiFXhH5/RVNTc/+y+0e3natyiNRC8nhMFsWwAwvCdqJEuJWqOAfF3r8eN3RmyTl3UDBkJiRz+sF1TXx+e85Uii9YddfCeYldvCO/an/wYD7ZhKUhL/EfqmShkeLvwxo37OJBcYGyxtba5jnCJ5S5hbLgzwk69eWQ0Oy7tkkXbYMs83bPdaoVMwOppGpJHcoZmlZMyuZ+bUR65aW5RQO7HEY+xk9VBL5vR6wORkKyJLxWBZDS/PCdY6N3JFaX1vgyPQJtomXbE5gDKtEgAOQ==,iv:LnQ1O1dHWFpYSAyrZ8cneklZmlif28beUK1Onb2ZLko=,tag:xhwgp9TfwFyvs6TrWm1+Pw==,type:str]
type: Opaque
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZVBCY2tseUZJUVlaeWp4
            Uk1adXl4NWdrUkswL2pnWlROWnhPWWZNdVhVCnVCZGdsanEvUEczYVY4d3hwVjJo
            Z3NoMXBjTGpIUmxJK3RraGxIem9LQ3MKLS0tIGQrTDZDanRPakZ5OFY5N2lQUFFs
            aHhIeWp1Snd6V3ZQalBwRml0RjhWOUkKgKpFYnYLLhirKGrBorL9KnOWjlJbZEQZ
            SqtRQTXCawu83gW5js1f4LU3seqXGjfSr+2Te3Wy5emQMzg6LqtzFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-21T10:13:05Z"
    mac: ENC[AES256_GCM,data:JOMQTEf0Xedqh4EP4qGQVywZKGpIpPTe5S1S8a6mhcNjta0AD5osWQ2QxCaZcGiPSP1Sg8nnEkX9XbCtFSGhQH25lw1jcLCPf8t4KVvX8X+2h6CFcVruxv2sjsVt+UogtfLsgL1jIl+thNoQsmjYppd1Nl16mubhiyv7e4tiYPc=,iv:vEuPp/haVe5v8/9/lGG3NGMZc5X1c2SPlANgqmwAiKU=,tag:y6Bld+rJ9hw0cAdaw9kVxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
