apiVersion: v1
kind: Secret
metadata:
    name: onepassword-token
    namespace: general-system
stringData:
    token: ENC[AES256_GCM,data:sFFVZkA++WnzUwtVwCNWXAKsm1/GjOo1GZfOgo1cg7z2JsWXGs/HAlfZEFAThFVRRss95AywC4AEgpWB4GzC4FMJ0vkhMWotEMxj/zjFAZvOExqHP/u2yu8VZ/MllmvajBc3G7BZvMc1opNCezQFi+g47jFoQNTEUxps85C/Crqgu1dRH+vMxXWNVed3XoAfbBGduCR55Wqnz+AbKaXtqP1mrQiUUE0X7Bmkq0z78ZaeZ0d66+H9+ugPmQ8BGBo5HxazJoVQ3r7CwIS5K3hK20YHdn3L08zD3uDX/Sd0gYwPcbFbbCnk7QI4IkW8U4nia9EUiS1qnSiw2ow53hWIRBn1xgDrZ2QLQs3TZZWmn7PbJUJPBBeQElWg/uhwtzJCX0ETxDZJ3l8oWKSvBYLeOecvgF8AqBj19TskqzNSfMyF3OCt3swDiuAKCfuSluI9x3LfOGYysGhNKbZr0pgmVDz3nDLzV0BYXFdGGN09rYo1ExnlsHSA0fsmjEellFshwEhjQXK7/MMrvS0BA5rLK94t3Whrkflq7cH06CYXCA8mw+2fbkNvqxYucEXW0onTvCufwznDlJnQLDjT3PXbGZEYpOVkiuyzwL3VwXgIH9iKJKqlF8mEBriwCx1npXvbmkMm2YHV+17fDPvHZ1CJpkZjPovgQSQaZt8FNpKEw/pWryGDuRWHGfUYrmTChaHjhA+bJ8OsqZ00jdi9cZBXrQTPMF6etDeMaTVZX0AI+x7TLCJxvMeYXPZSF4HUcEi6ar82FjCpzpEIFio0WbCT/3AqfTugtpNVhUcckYXkjsWK6AxNOQP87XuS3LXX/7S5rh8J8cpUkadE4q50LWiQj0Yhl/ZBP6wGxKM4xk+k+JWgipZAFB0pichdK/wejvW4oBuNFh2/Od7MVSKgzJSYy2v7aTmYLGoPdUt8eXcHZLcFD37t9w9XBd7SMj3YWTlPQgf2LSmREmPIs5plfMBysnSR+6ttLA0uJLFj5dIsi+pEvw==,iv:r/9iO4Uoub2kcsPUzwzO5CGZbR2x47s545RmNVlKG7k=,tag:yeHhFjL1krAEkb05qxsV1g==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMDV4aFlSQU5DeklheVhp
            aEdUbUVSSlZMcGpZdjlDRW1KbVpqYmNoRTNvCi9vckwwWTJOSXpHdFpQNW5MNXRE
            RXJFRTVOcDFnUVdlclk1S29oQTRqanMKLS0tIFB0enN6SlE1U2U2Z2tYWEZEaEhl
            c0tEOHdwSXZwaTBsZVdSMEo5dnBrd1EKygbstYTkvJt3aXjD3EioHaUyP6BM1NrQ
            7NbrBQNy0XCGfdrNzfRXMKhOXxG1PPcjlBuCKbU5xNMucEU59FAtAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T08:33:14Z"
    mac: ENC[AES256_GCM,data:giQXcLqsVV61GOS9dY7HzCGUlioJ2ysHymyDANqDm+skDXQiSxjy5ZsUkgajlaSJIHrCiqecj6lC3NYhy1zaVbuhYtQBc9oC4+b+b1MnCnUfDU4MwTPpxOrelEPg3U7TG0IIR/uPX0K/ywGq8brs6/y+LP2s5pWl+egvpMkzfFc=,iv:9ZC0JOwYwusONd9GrVBoFWSqGEgzaF1D4683T0KKduw=,tag:MsRlzQbzwS4ZH7lsJ2XXiQ==,type:str]
    version: 3.13.1
