# Cloudflared tunnels.
#
# Why two tunnels:
# - `firefly`     — the in-cluster cloudflared DaemonSet (home k3s "firefly").
#                   Has routes into *.svc.cluster.local for the apps the home
#                   network actually hosts. THIS is what serves cc/cc-pro/
#                   atlantis/zoey/overseerr/radarr.
# - `firefly_oci` — cloudflared containers running on the OCI MikroTik CHRs
#                   (see terraform/oci/modules/mikrotik/). These can't reach
#                   the home cluster while the OCI<->home VPN is down, so they
#                   must NOT share the firefly tunnel — when they did, ~33%
#                   of incoming requests for any firefly host got load-
#                   balanced to the OCI side, where they 502'd on the
#                   unreachable upstreams (postmortem 2026-05-24).
#
# tunnel_secret is required by the resource but is only used at *creation*;
# importing an existing tunnel doesn't let us read the original secret back
# from the CF API. We supply a placeholder and ignore_changes so the import
# doesn't try to rotate. A genuine rotation (planned follow-up) would unset
# ignore_changes, set a real secret, and push the new credentials to wherever
# cloudflared reads them.

resource "cloudflare_zero_trust_tunnel_cloudflared" "firefly" {
  account_id = var.account_id
  name       = "firefly"

  # Placeholder; ignored after import. `secret` must be base64 of a 32+ byte
  # value but is only consumed at create-time. (Provider v4 renamed this from
  # tunnel_secret → secret somewhere along the line.)
  secret = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

  lifecycle {
    ignore_changes = [secret]
  }
}

# Random secret for firefly_oci. Generated by terraform on first apply,
# stored in state. The token (which is what cloudflared actually uses) is
# derived from {account_id, tunnel_id, secret} via the CF API data source
# below and exported for the runbook to copy into OCI Vault.
resource "random_password" "firefly_oci_tunnel_secret" {
  length  = 64
  special = false
}

resource "cloudflare_zero_trust_tunnel_cloudflared" "firefly_oci" {
  account_id = var.account_id
  name       = "firefly-oci"
  secret     = base64encode(random_password.firefly_oci_tunnel_secret.result)
}

# Minimal ingress for the OCI tunnel — a catch-all 404 only. The OCI MikroTik
# CHRs currently can't proxy anything useful (no working route to the home
# k3s cluster). Real routes get added here once the OCI<->home VPN is up and
# we decide what OCI-side traffic should funnel through this tunnel.
resource "cloudflare_zero_trust_tunnel_cloudflared_config" "firefly_oci" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly_oci.id

  config {
    ingress_rule {
      service = "http_status:404"
    }
  }
}

# NOTE: the firefly_oci connector token is no longer surfaced via Terraform.
# `cloudflare_zero_trust_tunnel_cloudflared_token` is a v5-only data source and
# isn't in the pinned provider (~> 4.40 → 4.52.7), so it failed `apply` ("does
# not support data source") even though it was unrelated to whatever was being
# changed. The token was a one-time copy into OCI Vault
# (cloudflared-tunnel-token-firefly-oci) and isn't needed at plan/apply time. To
# re-fetch it, use the CF API or bump the provider to v5 (a wider migration).

output "firefly_oci_tunnel_id" {
  description = "Tunnel ID for firefly-oci. Needed for the cfargotunnel CNAME if/when OCI-side hostnames are added."
  value       = cloudflare_zero_trust_tunnel_cloudflared.firefly_oci.id
}

# Ingress for the firefly tunnel. Mirrors the dashboard's current config:
# - overseerr.sargeant.co  -> http://overseerr.media.svc.cluster.local:5055
# - <anything else>        -> http_status:404
resource "cloudflare_zero_trust_tunnel_cloudflared_config" "firefly" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly.id

  config {
    warp_routing {
      enabled = true
    }

    ingress_rule {
      hostname = "overseerr.sargeant.co"
      service  = "http://overseerr.media.svc.cluster.local:5055"
      origin_request {}
    }

    ingress_rule {
      hostname = "radarr.sargeant.co"
      service  = "http://radarr.media.svc.cluster.local:7878"
      origin_request {}
    }

    # GitHub webhooks → Atlantis (firefly cluster). This + the cloudflare
    # tunnel auto-creates the public CNAME atlantis.sargeant.co →
    # <tunnel-id>.cfargotunnel.com so the App's webhook URL resolves.
    ingress_rule {
      hostname = "atlantis.sargeant.co"
      service  = "http://atlantis.automation.svc.cluster.local:80"
      origin_request {}
    }

    # n8n-mcp — the remote MCP endpoint (kubernetes/apps/n8n-mcp) served at the
    # /mcp path on this SAME host, so Claude can build/edit n8n workflows without a
    # separate subdomain. cloudflared evaluates top-to-bottom, so this MUST precede
    # the n8n catch-all below: ^/mcp(/?$) → the MCP service; everything else (UI,
    # /api, /form, and n8n's own MCP-trigger /mcp/<id> URLs, which carry a subpath)
    # falls through to n8n. Gated by the n8n-mcp CF Access service token
    # (access_apps.tf → n8n_mcp); the MCP reaches n8n in-cluster so n8n's REST API
    # stays private.
    ingress_rule {
      hostname = "n8n.magmamoose.com"
      path     = "^/mcp/?$"
      service  = "http://n8n-mcp.automation.svc.cluster.local:3000"
      origin_request {}
    }

    # n8n — self-service automation UI plus the ops-request form and the
    # approval *resume* webhooks. Now reachable off-LAN via this tunnel and
    # gated by the Caleb-only Cloudflare Access app (access_apps.tf), so the
    # browser-link approval pattern ($execution.resumeUrl on n8n.magmamoose.com)
    # works remotely, not just on the LAN. Pairs with the proxied CNAME
    # external-dns publishes from kubernetes/apps/n8n (the magmamoose Ingress).
    # n8n.sargeant.co stays a LAN-only alias (no tunnel, no Access).
    ingress_rule {
      hostname = "n8n.magmamoose.com"
      service  = "http://n8n.automation.svc.cluster.local:5678"
      origin_request {}
    }

    # Public OpenAI-compatible LiteLLM endpoint for Warp custom inference.
    # Keep the normal litellm.sargeant.co host LAN/VPN-only; Warp's backend
    # rejects private RFC1918 resolutions, so this hostname enters through the
    # Cloudflare edge and firefly tunnel instead. Only the minimal OpenAI API
    # paths are routed; UI/admin/model-management paths fall through to 404.
    ingress_rule {
      hostname = "litellm-warp.sargeant.co"
      path     = "^/v1/chat/completions/?$"
      service  = "http://litellm.automation.svc.cluster.local:8080"
      origin_request {}
    }
    ingress_rule {
      hostname = "litellm-warp.sargeant.co"
      path     = "^/v1/models/?$"
      service  = "http://litellm.automation.svc.cluster.local:8080"
      origin_request {}
    }
    ingress_rule {
      hostname = "litellm-warp.sargeant.co"
      service  = "http_status:404"
    }

    # GitHub PR-review webhooks → comment-commander (firefly cluster).
    # Pairs with the explicit proxied CNAME in
    # terraform/cloudflare/dns-magmamoose/prod/terragrunt.hcl
    # (comment-commander.magmamoose.com → <tunnel-id>.cfargotunnel.com).
    # Same pattern as atlantis.sargeant.co / radarr.sargeant.co.
    ingress_rule {
      hostname = "comment-commander.magmamoose.com"
      service  = "http://comment-commander.comment-commander.svc.cluster.local:8000"
      origin_request {}
    }

    # comment-commander-pro dashboard (firefly cluster). Gated by the
    # self_hosted Cloudflare Access app in access_apps.tf (Caleb only —
    # the dashboard has no in-app auth/paywall yet). Pairs with the proxied
    # CNAME in dns-magmamoose/prod/terragrunt.hcl.
    ingress_rule {
      hostname = "comment-commander-pro.magmamoose.com"
      service  = "http://comment-commander-pro.comment-commander-pro.svc.cluster.local:8000"
      origin_request {}
    }

    # Diatreme Pro dashboard (firefly cluster) — the apex diatreme.magmamoose.com.
    # Supersedes comment-commander-pro as comment-commander folds into Diatreme;
    # leave the cc-pro rule above until diatreme-pro is verified live, then prune.
    # Gated by the self_hosted Access app in access_apps.tf (Caleb only). DNS is
    # published by external-dns from the diatreme-pro k8s Ingress (not an explicit
    # Terraform CNAME). NOTE: the Diatreme *worker* is a Cloudflare Worker at
    # api.diatreme.magmamoose.com — served directly by CF, not tunneled here, and
    # intentionally NOT Access-gated (it's the OSS engine API; it authenticates
    # callers itself via bearer / HMAC / OIDC).
    ingress_rule {
      hostname = "diatreme.magmamoose.com"
      service  = "http://diatreme-pro.diatreme-pro.svc.cluster.local:8000"
      origin_request {}
    }

    # TEMPORARY sargeant.co mirrors of the two comment-commander hostnames,
    # added while magmamoose.com is on Tucows clientHold (TLD delegation
    # withheld → nothing under magmamoose.com resolves). See memory:
    # project_magmamoose-clienthold-swap.md. Removal checklist when the
    # hold lifts:
    #   1. `whois magmamoose.com` no longer shows clientHold
    #   2. delete these two ingress_rule blocks
    #   3. delete matching CNAMEs in terraform/cloudflare/dns/prod/terragrunt.hcl
    #   4. delete API-managed Access app "Comment Commander Pro (sargeant.co swap)"
    #      (aud 3c5f1f326b45..., domain comment-commander-pro.sargeant.co)
    # cc-pro is still gated by Access via the (API-managed) app above;
    # comment-commander has no Access — same as the magmamoose flavour.
    ingress_rule {
      hostname = "comment-commander.sargeant.co"
      service  = "http://comment-commander.comment-commander.svc.cluster.local:8000"
      origin_request {}
    }
    ingress_rule {
      hostname = "comment-commander-pro.sargeant.co"
      service  = "http://comment-commander-pro.comment-commander-pro.svc.cluster.local:8000"
      origin_request {}
    }

    # Zoey — project-intelligence dashboard (firefly cluster). Public so
    # Slack's interaction webhook can POST to /api/v1/slack/interaction;
    # the UI is gated by the Zoey Cloudflare Access app (access_apps.tf),
    # the /api/v1/slack/* path bypassed there. Pairs with the proxied
    # CNAME external-dns publishes from the k8s Ingress
    # (zoey repo: k8s/base/ingress.yaml → target=<firefly-tunnel>).
    #
    # Two rules: backend paths first (more specific), frontend catch-all
    # second. cloudflared evaluates ingress rules top-to-bottom.
    ingress_rule {
      hostname = "zoey.sargeant.co"
      path     = "^/(api|mcp|health)(/|$)"
      service  = "http://zoey-backend.zoey.svc.cluster.local:8000"
      origin_request {}
    }
    ingress_rule {
      hostname = "zoey.sargeant.co"
      service  = "http://zoey-frontend.zoey.svc.cluster.local:3000"
      origin_request {}
    }

    # ── AppSec / dev tooling (firefly cluster) ───────────────────────────────
    # Caldrith GitHub App webhook — MUST be publicly reachable so GitHub's
    # delivery IPs can POST to the apex (caldrith.magmamoose.com). No Access
    # gate (GitHub can't authenticate through Access); the webhook secret + HMAC
    # signature authenticate payloads. Supersedes the retired safe-settings app.
    ingress_rule {
      hostname = "caldrith.magmamoose.com"
      service  = "http://caldrith.caldrith.svc.cluster.local:8000"
      origin_request {}
    }

    # Nievah GitHub App webhook — MUST be publicly reachable so GitHub's delivery
    # IPs can POST to the apex (nievah.magmamoose.com). No Access gate (GitHub
    # can't authenticate through Access); the webhook secret + HMAC signature
    # authenticate payloads. Auto-reviews PRs on allowlisted MagmaMoose repos.
    ingress_rule {
      hostname = "nievah.magmamoose.com"
      service  = "http://nievah.nievah.svc.cluster.local:8000"
      origin_request {}
    }

    # Chargate token broker — MUST be publicly reachable so GitHub Actions runners
    # can POST their OIDC token to /token (api.chargate.magmamoose.com). No Access
    # gate (runners can't authenticate through Access); the broker verifies each
    # caller's OIDC token itself and mints a repo-scoped Chargate[bot] token.
    ingress_rule {
      hostname = "api.chargate.magmamoose.com"
      service  = "http://chargate.chargate.svc.cluster.local:8000"
      origin_request {}
    }

    # DefectDojo UI — fronted by oauth2-proxy (Google SSO, @magmamoose.com).
    # The proxy forwards to defectdojo-django and bypasses auth for /api/v2 +
    # /webhook (token/secret-authenticated, non-browser clients).
    ingress_rule {
      hostname = "defectdojo.magmamoose.com"
      service  = "http://oauth2-proxy.security.svc.cluster.local:4180"
      origin_request {}
    }
    # Legacy alias kept during the hostname move to magmamoose.com.
    ingress_rule {
      hostname = "defectdojo.sargeant.co"
      service  = "http://oauth2-proxy.security.svc.cluster.local:4180"
      origin_request {}
    }

    # Dependency-Track on a single public hostname. cloudflared evaluates rules
    # top-to-bottom, so the /api split MUST precede the frontend catch-all:
    #   dependencytrack.magmamoose.com/api/* (REST API, all methods) → apiserver
    #   dependencytrack.magmamoose.com/<rest>                        → frontend SPA
    # The frontend is nginx serving static files and 405s any non-GET method, so
    # SBOM uploads (POST /api/v1/bom, multipart, a few MB — well under Cloudflare's
    # edge body limit, no tunnel-side cap needed) MUST hit the apiserver here.
    # Mirrors the zoey.sargeant.co api/frontend split above. frontend.apiBaseUrl
    # now points at this same host, so the SPA is same-origin too.
    ingress_rule {
      hostname = "dependencytrack.magmamoose.com"
      path     = "^/api(/|$)"
      service  = "http://dependency-track-api-server.security.svc.cluster.local:8080"
      origin_request {}
    }
    ingress_rule {
      hostname = "dependencytrack.magmamoose.com"
      service  = "http://dependency-track-frontend.security.svc.cluster.local:8080"
      origin_request {}
    }
    # Dedicated API hostname — kept as a backward-compatible fallback. The SPA no
    # longer needs it now that it's same-origin, but it's harmless for any direct
    # API client still pointed here.
    ingress_rule {
      hostname = "dependencytrack-api.magmamoose.com"
      service  = "http://dependency-track-api-server.security.svc.cluster.local:8080"
      origin_request {}
    }
    # Legacy aliases kept during the hostname move to magmamoose.com.
    ingress_rule {
      hostname = "dependency-track.sargeant.co"
      service  = "http://dependency-track-frontend.security.svc.cluster.local:8080"
      origin_request {}
    }
    ingress_rule {
      hostname = "dependency-track-api.sargeant.co"
      service  = "http://dependency-track-api-server.security.svc.cluster.local:8080"
      origin_request {}
    }

    # git-pull-request-dashboard — static SPA, fronted by oauth2-proxy
    # (Google SSO, @magmamoose.com). The GitHub PAT is still entered client-side.
    ingress_rule {
      hostname = "pullrequests.magmamoose.com"
      service  = "http://oauth2-proxy.automation.svc.cluster.local:4180"
      origin_request {}
    }
    # Legacy alias kept during the hostname move to magmamoose.com.
    ingress_rule {
      hostname = "pr-dashboard.sargeant.co"
      service  = "http://oauth2-proxy.automation.svc.cluster.local:4180"
      origin_request {}
    }

    # Authentik — the identity provider (kubernetes/apps/authentik). It carries its
    # own auth, so no Access gate. external-dns publishes the CNAME from the k8s
    # Ingress; the tunnel routes to the server Service.
    ingress_rule {
      hostname = "authentik.magmamoose.com"
      service  = "http://authentik-server.authentik.svc.cluster.local:80"
      origin_request {}
    }

    # SonarQube — self-hosted code-quality + security (firefly cluster). DNS is
    # published by external-dns from the k8s Ingress (kubernetes/apps/sonarqube).
    # Its security findings are imported into DefectDojo (security-integrations).
    ingress_rule {
      hostname = "sonarqube.magmamoose.com"
      service  = "http://sonarqube-sonarqube.security.svc.cluster.local:9000"
      origin_request {}
    }

    # Backstage developer portal (firefly cluster) — Red Hat Developer Hub
    # community build (kubernetes/apps/backstage). Service is <release>-developer-hub.
    ingress_rule {
      hostname = "backstage.magmamoose.com"
      service  = "http://backstage-developer-hub.core.svc.cluster.local:7007"
      origin_request {}
    }

    # Grafana — kube-prometheus-stack observability dashboards (firefly cluster).
    # DNS is the proxied CNAME external-dns publishes from the k8s Ingress
    # (kubernetes/apps/kube-prometheus-stack); Access-gated (Caleb) in access_apps.tf.
    # grafana.sargeant.local stays a LAN-only alias (no tunnel).
    ingress_rule {
      hostname = "grafana.magmamoose.com"
      service  = "http://kube-prometheus-stack-grafana.observability.svc.cluster.local:80"
      origin_request {}
    }

    # GitHub usage dashboard (firefly cluster) — githubusage.magmamoose.com.
    # Gated by the self_hosted Cloudflare Access app in access_apps.tf (Caleb
    # only — it surfaces org billing, no in-app auth). external-dns publishes the
    # proxied CNAME from the k8s Ingress annotations. Placed last (before the
    # catch-all) so the plan is a clean append, not a mid-list reorder.
    ingress_rule {
      hostname = "githubusage.magmamoose.com"
      service  = "http://github-usage-dashboard.github-usage-dashboard.svc.cluster.local:8000"
      origin_request {}
    }

    # GitHub contributions dashboard (firefly cluster) — githubcontributions.magmamoose.com.
    # Gated by the self_hosted Cloudflare Access app in access_apps.tf (Caleb only —
    # it surfaces personal commit/effort analytics, no in-app auth). external-dns
    # publishes the proxied CNAME from the k8s Ingress annotations. Placed last
    # (before the catch-all) so the plan is a clean append, not a mid-list reorder.
    ingress_rule {
      hostname = "githubcontributions.magmamoose.com"
      service  = "http://github-contributions.github-contributions.svc.cluster.local:8000"
      origin_request {}
    }

    # Timesheet dashboard (firefly cluster) — uren.calebsargeant.com. Reconstructs
    # Caleb's PinkRoccade "Uren" sheet from a published-calendar ICS + GHE commits.
    # Gated by the self_hosted Cloudflare Access app in access_apps.tf (Caleb +
    # his manager Marc, email-OTP). calebsargeant.com is in the same Magma Moose
    # account; external-dns publishes the proxied CNAME from the k8s Ingress
    # annotations (calebsargeant.com added to its domainFilters). Placed last
    # (before the catch-all) so the plan is a clean append.
    ingress_rule {
      hostname = "uren.calebsargeant.com"
      service  = "http://github-timesheet.github-timesheet.svc.cluster.local:8000"
      origin_request {}
    }

    # Cloudflared requires the last rule to be a catch-all with no hostname.
    ingress_rule {
      service = "http_status:404"
    }
  }
}

# Private RFC1918 routes directed to the firefly tunnel (k3s cluster).
resource "cloudflare_zero_trust_tunnel_route" "rfc1918_10" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly.id
  network    = "10.0.0.0/8"
  comment    = "Route 10.0.0.0/8 private network through firefly tunnel"
}

resource "cloudflare_zero_trust_tunnel_route" "rfc1918_172" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly.id
  network    = "172.16.0.0/12"
  comment    = "Route 172.16.0.0/12 private network through firefly tunnel"
}

resource "cloudflare_zero_trust_tunnel_route" "rfc1918_192" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.firefly.id
  network    = "192.168.0.0/16"
  comment    = "Route 192.168.0.0/16 private network through firefly tunnel"
}
