apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ollama-lan
  namespace: automation
  labels:
    app: ollama-lan
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  ingressClassName: traefik
  rules:
    - host: ollama.sargeant.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-lan
                port:
                  number: 11434
    - host: ollama.sargeant.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ollama-lan
                port:
                  number: 11434
  tls:
    - hosts:
        - ollama.sargeant.co
      secretName: ollama-lan-tls
