apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.enc.yaml
  - cluster.yaml
  - scheduled-backup.yaml
  - prometheusrule.yaml
  - externalsecret-oci-backup.yaml
  - externalsecret-nextcloud-admin.yaml
  - externalsecret-neondb-owner.yaml
