apiVersion: v1
kind: Secret
metadata:
    name: wordpress-db
    namespace: wordpress
type: Opaque
stringData:
    db-user: ENC[AES256_GCM,data:du/qCDOl7b8m,iv:CT6BBznSdcMvprj0/722PMBacR8leG5k3A20N5iKpzA=,tag:3Oz307QoU5m3PFxVzbirow==,type:str]
    db-password: ENC[AES256_GCM,data:gCfLGJq0wfpDIfL7p4MPeERmp0+7RRLaMysSjX7nzN6Qk3bQmmibk1leND8=,iv:YXij+Llbvpo6lV35+yM7IeNO796n9vyncgn7XT1RBGw=,tag:UGFAQaSA/24wS8WjzGyQXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJT0pyMEFVRGtFUDhtZ1JM
            dDF5OUNldVVZbWx5ay8vajk2MTlpYzg1UFhFCkJhVG1vdTZoV1VwRnlvaUNOZk42
            UXpzNkk0UldERDlreGtXTnY1L01RNncKLS0tIEZPVW1PVHZzemZFNzR1Tmw3V2lQ
            Nngrck5tbE1NUEFNaFA4SE9hbE9lSFkKfegxenyFVtV+JKYafwChuE0P29FNCTPX
            zgmLZO36WxisVb1tOy6wc9tCxjVE6W9aE4GZaT9VkbyITKOoKajMtQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYmRieEcvQ2FvK0RnQTNh
            Q1hVejBSeU5xeFAvQ3JpMFdWL0pYZ2g0eDJnClhVZE1PMkpCSXNXNkpmeGhxQzVZ
            MXl2NGF2U0poUWV1RXhVT1B3bkxPM0kKLS0tIFJ4WEhQc2RCeEswOWUzSjFXd2Rl
            RXpJSlBJUWhRZW1YOXkzLzkrQno3cWsKC0VG5bMxMucmCjiWj8pOOGjwwQs0/icn
            8mT1t2Z02qZuZfBguKE7FRvPg5Py0jbty37N31y7QkEwekZcN6Q8hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-01-18T19:15:47Z"
    mac: ENC[AES256_GCM,data:nFi56oZmDOYvtVFpNM/dzVjjQa8pqeSZF+DEYUMWKvYjHLAxYfh738A34JmLHQN/EPfIC2qY9c1A2AgBJkcDGo0JgU96SdBEtDhbrFXFd9/cJj6XeJTsmT33jkvsRTzCrS9Fu2/9kAQXh5PBRNk7c0Kdx8bD2HiQTGheVgmxPEw=,iv:iSOPbvdXLT5MFL7xMDpVMLtl7uxu2SCS6XFJ+etfAQo=,tag:z3MkiEu2g4DWLLDyr/4ifA==,type:str]
    version: 3.11.0
