apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - statefulset.yaml
  - service.yaml
  - externalsecret.yaml
  - setup-job.yaml
  - externalsecret-backup-oci.yaml
  - backup-cronjob.yaml
