apiVersion: v1
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:bmKSF3Q1YwK4W2eb6qWUu00aLn0oAM3ABe3URs3L6KjRi8dZ2U3+roynDmQ=,iv:7wGMGNIStCysurzWkDNZummzkoOxbQpZ7Dqf8iVbE/4=,tag:LqdQxNeJDYoU65LOeqn0lg==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:MmMHnCqQYWeBM6uFQOJtwR1MElr+vzhwprHaskz1qhLJ+gS4qlt5UgtEn71lb21ytEjIfolq+PDaaaUYZIf9+5/0eXGTBYEnqEzu4w==,iv:mjQtgJcelx+jcHsSge2pedorZxSrCuzBN//juHlx4p8=,tag:1n6TaOibmR1ry++CloYzEw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:FbR7QIy8YzJqiM1fQm/InWEouQatcs96Ah5209O7Pxc9dFBQI1zYVWMF+xM=,iv:mhZ4pcvoVzJrvCOckgKJ3R5tBe3i7p+2x9+241zjMhY=,tag:NDquNrYrMi7fbnVsCbCmow==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:H988MqUxHwZT/ohaYjbvpXkycBUManXEfRM9mVwJ2A6z8JgrYg9fDWhQrCg=,iv:zyb1ftZ0td5A6vaGMD/lQXasTKRrJBSAR7TA8TIXjRk=,tag:Ado3bOwZ6bY8uHHaakmzdQ==,type:str]
kind: Secret
metadata:
    name: streaming-sync-secrets
    namespace: media
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRUVGY2Q1Y1QrRWkvQ1cr
            SDBsOU90VHd4OG1jUmRjdXFSYjhLSVYvaVZBClEraEh0QzdteXVZcWZEamtGaGJ4
            OXNzZFArMk5YcFJMTDJKUFRZUWhUMzgKLS0tIHFDUE1WWFU1VjZqNis2MkQzZEFp
            aTJIaWViVUpWWnAwTnRHRmFzaU1xcFEKhBFXOIkCo/qw1tfLnkBFQGdZfswATk91
            o7o+Kvr/ot+dBT3COY/Iw/UjUVgGnMUM1H04/RvfvR0DQs1wZsg9Rg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T10:57:39Z"
    mac: ENC[AES256_GCM,data:mVB/P7PMyY3YURl0WCBQ72k1gdGkfh42HfRHhulfc4S+RjTlYXN8Y5cfZbuqPB62D+c3EZHElHm2GKuHZvKaVZida/tueDEMZGUEGhI7d1zMInAWsjBdPgaL84/A10WEI2KK0cUgoybmAlrQjICPaWnptdKqe+dsxkeuhvObqAw=,iv:tmPET7mdsSiRsqZxl2KdjxmqXSjaS2hBtoUDTwBoREk=,tag:9nNz47PVzpe7jSYFh/0spQ==,type:str]
    version: 3.11.0
