apiVersion: v1
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:bmKSF3Q1YwK4W2eb6qWUu00aLn0oAM3ABe3URs3L6KjRi8dZ2U3+roynDmQ=,iv:7wGMGNIStCysurzWkDNZummzkoOxbQpZ7Dqf8iVbE/4=,tag:LqdQxNeJDYoU65LOeqn0lg==,type:str]
    SLACK_BOT_TOKEN: ENC[AES256_GCM,data:MmMHnCqQYWeBM6uFQOJtwR1MElr+vzhwprHaskz1qhLJ+gS4qlt5UgtEn71lb21ytEjIfolq+PDaaaUYZIf9+5/0eXGTBYEnqEzu4w==,iv:mjQtgJcelx+jcHsSge2pedorZxSrCuzBN//juHlx4p8=,tag:1n6TaOibmR1ry++CloYzEw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:FbR7QIy8YzJqiM1fQm/InWEouQatcs96Ah5209O7Pxc9dFBQI1zYVWMF+xM=,iv:mhZ4pcvoVzJrvCOckgKJ3R5tBe3i7p+2x9+241zjMhY=,tag:NDquNrYrMi7fbnVsCbCmow==,type:str]
    TMDB_API_KEY: ENC[AES256_GCM,data:H988MqUxHwZT/ohaYjbvpXkycBUManXEfRM9mVwJ2A6z8JgrYg9fDWhQrCg=,iv:zyb1ftZ0td5A6vaGMD/lQXasTKRrJBSAR7TA8TIXjRk=,tag:Ado3bOwZ6bY8uHHaakmzdQ==,type:str]
kind: Secret
metadata:
    name: streaming-sync-secrets
    namespace: media
sops:
    age:
        - recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZ0lac1o3eHRhVkRRcWI3
            OXJIdFdjdUsxTEhlRWVzdHBwNjQ0ZTNVM3dBClhMd3Q3SmZvVmpXbVFtZ09kNlo3
            Q3M0SklZcHZQaXYrN2dnajk0dVQyNjAKLS0tIDFlUmI0c0NJaFA4TWtKTUd5Z2ty
            UmxjZkFocFhkTXNaK2NGVUtkMThLOW8Kn5IDMVmI6+RkMkc57kv8uUiOg2QUfjqo
            TL5vrMCgvNzo8mhEL4i1aVwl0bkZjjLhpFUtAS81vg34RooOMdYb+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-01T10:57:39Z"
    mac: ENC[AES256_GCM,data:mVB/P7PMyY3YURl0WCBQ72k1gdGkfh42HfRHhulfc4S+RjTlYXN8Y5cfZbuqPB62D+c3EZHElHm2GKuHZvKaVZida/tueDEMZGUEGhI7d1zMInAWsjBdPgaL84/A10WEI2KK0cUgoybmAlrQjICPaWnptdKqe+dsxkeuhvObqAw=,iv:tmPET7mdsSiRsqZxl2KdjxmqXSjaS2hBtoUDTwBoREk=,tag:9nNz47PVzpe7jSYFh/0spQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
