apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-automation.yaml
  - deployment.yaml
  - ingress.yaml
components:
  - ../../../components/pod-gateway-client
  - ../../../components/resource-profiles/c.micro
  - ../../../components/node-selectors/native-cloud
