#!/usr/bin/env bash
#
# Regenerate the SOPS-encrypted OCI API credentials Secret for a cluster.
#
# Why this exists: the OCI API private keys in 1Password are stored FLATTENED —
# their PEM line breaks are spaces. Pasting one straight into a YAML block scalar
# produces a Secret that decrypts cleanly but that the OCI SDK rejects with
#
#     bad configuration: PEM data was not found in buffer
#
# which reads like an auth problem and is not one. This script strips the
# markers, discards all whitespace from the body, re-wraps at 64 characters, and
# writes the result base64-encoded into `data:` so no YAML round-trip can reflow
# it. It verifies the key parses and that its public fingerprint matches the
# `fingerprint` field before writing anything.
#
# Usage:
#   scripts/rebuild-oci-credentials.sh franklinhouse
#   scripts/rebuild-oci-credentials.sh firefly
#
# Requires: op (authenticated), sops, openssl, python3.

set -euo pipefail

CLUSTER="${1:-}"
case "$CLUSTER" in
  franklinhouse)
    ITEM='op://Franklin House/mbcio5qom6xfj6glkkwtiim2za'
    DEST='kubernetes/clusters/franklinhouse/infrastructure/services/stack/external-secrets/oci-vault-credentials.enc.yaml'
    ;;
  firefly)
    ITEM='op://Magma Moose/thry5omisuq7pxy6fdbqm63vce'
    DEST='kubernetes/infrastructure/controllers/external-secrets/oci-vault-secret-enc.yaml'
    ;;
  *)
    echo "usage: $0 <franklinhouse|firefly>" >&2; exit 1 ;;
esac

for bin in op sops openssl python3; do
  command -v "$bin" >/dev/null 2>&1 || { echo "error: $bin is required" >&2; exit 1; }
done

TMP="$(mktemp -d)"
trap 'find "$TMP" -type f -exec shred -u {} + 2>/dev/null; rm -rf "$TMP"' EXIT INT TERM

op read "${ITEM}/private key" | tr -d '\r' > "$TMP/raw.txt"

python3 - "$TMP/raw.txt" "$TMP/key.pem" <<'PY'
import re, sys
raw = open(sys.argv[1], encoding="utf-8").read().strip()
m = re.search(r"-----BEGIN ([A-Z ]+)-----(.*?)-----END \1-----", raw, re.S)
if not m:
    sys.exit("error: no PEM markers in the 1Password 'private key' field")
label, body = m.group(1), re.sub(r"\s+", "", m.group(2))
lines = [body[i:i + 64] for i in range(0, len(body), 64)]
open(sys.argv[2], "w", newline="\n").write(
    f"-----BEGIN {label}-----\n" + "\n".join(lines) + f"\n-----END {label}-----\n")
PY

openssl pkey -in "$TMP/key.pem" -noout 2>/dev/null \
  || { echo "error: rebuilt PEM does not parse" >&2; exit 1; }

op read "${ITEM}/configuration" | tr -d '\r' \
  | grep -E '^[[:space:]]*fingerprint[[:space:]]*=' | cut -d= -f2- | tr -d '[:space:]' \
  | tr -d '\n' > "$TMP/fp.txt"

calc="$(openssl rsa -in "$TMP/key.pem" -pubout -outform DER 2>/dev/null | openssl md5 -c | awk '{print $2}')"
want="$(cat "$TMP/fp.txt")"
[[ "$calc" == "$want" ]] \
  || { echo "error: key fingerprint ($calc) != configured fingerprint ($want)" >&2; exit 1; }

{
  echo '---'
  echo "# OCI API signing credentials for ${CLUSTER}. Generated by"
  echo '# scripts/rebuild-oci-credentials.sh -- do not hand-edit.'
  echo '#'
  echo '# base64 `data:` on purpose: the 1Password copy of the key is stored'
  echo '# flattened (newlines as spaces) and must be re-wrapped, and base64 cannot'
  echo '# be reflowed by a YAML round-trip. Verified to parse and to match the'
  echo '# configured fingerprint before writing.'
  echo 'apiVersion: v1'
  echo 'kind: Secret'
  echo 'metadata:'
  echo '  name: oci-vault-credentials'
  echo '  namespace: external-secrets'
  echo 'type: Opaque'
  echo 'data:'
  echo "  privateKey: $(base64 -w0 < "$TMP/key.pem")"
  echo "  fingerprint: $(base64 -w0 < "$TMP/fp.txt")"
} > "$DEST"

sops -e -i "$DEST"
echo "wrote and encrypted $DEST (fingerprint verified)"
