apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: flux-system
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:OOjyFDknu1iWwh21rUdjtvo8HfbPIUn2YUdTtM2SVDCnwThGY+/BM7jTrwzRY0Qndy+cXaIjZgIx63d1scffnqopjfcG21csTdRRP5CEWtY2H8pmVaZOVNP0rcqCoUuSxRf6egvmZgJxwGxDCmU9r8b56u3nrcbgMlY7CM0zuJywpXqzObMDDQxJFcKhhfYWsS1OOsI6S1PfJbUyWP24WURZZvh2czXnXXPZd8KFTqlKLmZN7A98UfODzVqeXt6xGmxSrB5XhhTq2fGq1SukPRJlbye07OE9Sqb8kXvUUTO1klCKgj8TJqdOWnU10wz3YQpqVlUVcJ0=,iv:pRPYVme8srTbmVAkt+bGAT8yYBDlZEB776vwWLsMUeg=,tag:B3H8rMEdNjyZzUUscwLioA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTVk3TU5PYXNlMWc2Q0Nx
            dGFqUnN4YVZJbjZjZ2RpUS9HTEljOTYvREU4CjlZNHErQjlHWGhraGFWRjg0WnVq
            L2tiQXRBZUpMUkd2VXU3ZlMwcFVSUlUKLS0tIG5jcEhLRTVZZDF4Tyt5MUFkcXhr
            SUNKVmdBR3hQQ25vVkx3NlZCSVlITXcKPJu5OYHvPzmtENOUCu9eLWgFLhagmaQi
            57l8wKscW/zH5XTsRrvH7E4zGGHYYnHExrpUHot84adJi2sfVhiW8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T19:36:48Z"
    mac: ENC[AES256_GCM,data:5mkhLdvvtzvttF4ox/TSMuKlcAom5U7xOaq4rCz9BFw4KXlPNvdQnOE6uH7S9To3WVk2kZddwq1uEuPFlU3RN7k6UWffr1SK+9zjckGo94fsmyAhUBkBM64gE7XMPQISVluBC+vay4QfyMsC22OhRmJaL3G/HDSLevwDh5xP56w=,iv:rY1uXuglvcGwoAjK2Kc1k1AdRaFqwHOUwMnCWeiXLOo=,tag:vRcluIgP1mRdmDN61OLkhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
