apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter-exporter
          image: prom/blackbox-exporter:v0.25.0
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
          args:
            - "--config.file=/etc/blackbox-exporter/blackbox-exporter.yml"
          ports:
            - containerPort: 9115
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox-exporter
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config