apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - externalsecret.yaml
  - externalsecret-thanos-objstore.yaml
  - externalsecret-grafana-admin.yaml
  - dashboard-app-logs.yaml
  - ingress-grafana-lan.yaml
components:
  - ../../../components/node-selectors/mini
