apiVersion: v1
kind: ConfigMap
metadata:
    name: loki-config
    namespace: observability
data:
    loki.yaml: ENC[AES256_GCM,data:ZZz4zFlIpat9BnuwvX95Mvrlj75i8GLKrGQ26QpJXyCD6DeKD0HRef75HQzxST4a2gsbJU7ICItxkpkRQF/6sn5IKpWE4ic3utjc7fJ8W47L8MxXG7OLP/6pWMSyQGUvBAG1eGPe4QHEoS89VAosMT89QANjvClSMMWcleplzEoNSoWMBWJcdCvihMJoOabF9T+dHO57SZozuCh5cRx1JBCa5XRtt4QD+esceDz/5mL8Tcj1azBGVVs1+NKDaaoaOuqGaFKBlaapA80l6MmmrV0lm267X8O2YpbJYJuGsirbxk0XMGKxppwINu+ADzpMeBuFDwDc/p+Z5lGVdLl1nZTJgDq1iH7rANowsKCre4l5aDx5dA2en4M5L4joBa4AbRGvVS3KB/Hdeakq6qvh0Wqlu36ux4tTQ6PAR7p1EcVPEtJZnH5WVZPpkdIXdv8VPTd0K70gYWcftdlni6ADItUh8f3HznpPIJArlgzggP9N35CMAv9BtGUUFK2kIvsNqaNJXIoOy/K2mmx6ANidab5Pr0s3VP2EbFcQwgdjk7iqM3pUkJWI/6njorCa28UAZnu+7IQ4D9dGqQ4V5QU1A2knjNL5SPiXYhjuD96wQjWS8GfJbUuZKhIfuAZ0OHIaulYv4MIJDYaiqNbsU7man7Fl7cTOLZ2IS6wN9Z6LH93q9spdIVlTE1NU7CltDYvnJvifXoP00lJHfLaVpi4LROxadoPqj2Hq83HgOYL3F9/yrBxmYLXWcFJlE2loLWVlxQnoPCiMsY2eKFUuA/6oRjWRP5RRrlKjwYlXtdSVVUMofReCkg5dwbc+p7REHeagWY1HXz3TU6jiKh1VDMoOvNuF7ReLyn9qYdZns3b7hnH6N+Q9vsuNs746yAftHzvZJwTNpEbMD6v89msAq61vg66xr0lbGLIgwg5Rq0vxO7Mrpa8KpG7rwOgU6/F1FaXOyO9nn5YiJXMZSRzPnhzVGPRp5Gyruzb1tInkg/72hGlC0De2JHHs5fH+QOTlXlPhF9PZ1JOCfMkeY9f+nMCYxySBq+VAEKMYxKUxCDxehQ8Zbobd0diXCGNTBaLpZL+OoK74A6WGP32jXeuFjYtBFooxsGbJ3cYItdpdUPAGi+z5QOwKY8Jy/ZjHkXGOIGofMhjh8NA6SU0gr/SFUBK41OvBn9gfsINu7C3z9vvyu5IX83Sq5FABD+qxNr3OTRePGtTCaTV6tS7Pc6DGvD2MolsgYF9d+udO7Xifp3VzCoBAFD2qhWfGhGo0+pOUyEkKgI53tv/Sd10onk544of2VfW9AWqf4Nhjewvzd/IaUok0Q4TvE8f//SA5NEh8qlJSmVcGGkKGKcfYgq42UkCehxyChwEWBLohV4Ooxji2b2kcaKQKaDe78/ZOm0DgRNe6JAUZe9XmKQBpEQwjQjVFNuN5MPcij43yaeQgjVePDyBDCM1SJG6aPKR3/kA32ZUZXTIVN7tOgvqWxba3wg3xv9rTvtYE3E+aR6Ub1cU9up/tpsm9YUgWeNNCxwlcxbBW/cK4TFzTJtkq0cK9kxDmjFiZ8BlamMCMeKQfZe6kbhTOaeusr/jHwDy9bjSLMrSl2AdZ2albfsbXh8ZFqrbjlM8Hr9WW2degma9c+KDJe3PmDLcrsdmexhdd68v1TcsenC7bKmwCKhAodzXc2t5j27Ls2eJfk3F4ij6Zqmt3ISqPz6Q/pvUNFnggXI8wB5ax4Tgyp8jqg60PE2WpoI8kIxkA990cR9JMvtTRKbMB,iv:eGC0Bd1qwW++xQv/1uvseBjcn26QGPhXo2TVECucENc=,tag:1Co2/Ldo6jvokhI7U/6WFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWxSSExUanU3NXJ0ckxM
            TGpacGY1anJzK3lNa0ZPNFJrNTNxTW8va3owCnZyY2g1VzVBNEl3enJMM1c1eWdo
            OTRTSjRvNDFYUTl1M3FJRDVQdGlIQ2sKLS0tIGNETFZUakhZMlBLdzFvUkhMY3BQ
            cFBnTlhOY0hqclVEMStTblVybTF1VTAKfnfkZGWn3BswTNx8KyWoBETmBOtx0f+A
            rj+tR5yc0znOqfDrX0SXV+YLVeyCA1YnuWkfPGdXEn/TDVJfCxLGuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yj3wdeleng98w9rv46yh40ettc78r9k4r4wgnx7ja5zxmyt8qe7snjg0a0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcStxUmxIT2RTNXppN2Jn
            bjFWbnd2TENtWENNNEhLTmR4MzUzd0NBc1hFCllhL3FLTVFtQ2JJck14T3FPcGkr
            a0xpV3FoaitRL21vaFBxejBFNzg1QzgKLS0tIFBlR25YOTgrMDR3Ri8zQzBPUHFo
            THRWbkFjYm9LbzNCY0JFakV0NTliNVEKmAdncu/ORwMuLEr0qE1hlqDytgO4VrX7
            9LZLv3zNWRetoEVD584FhPImOg8R1CY8/n/JWTzbIt6dR/1nZH6K0g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c5k0q4adlrst6t003whpek86c87ymkdh9num9ha22uhwftvanyds6v2ctc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T08:33:27Z"
    mac: ENC[AES256_GCM,data:si+9vh2m4j5G52vK+Z85kHiL+APHYjzM4KiHHdlp49HTa/e7nM6kicuYlEgYDpA4GGnJJwA5udwrkIdQnzM00+ElHRsXZjr2OWBJ6QOWLwmPgplxUUedIu7pp8jvK/TvTzO/wBN70S59mETMSojMvS8XcUng63TXEoRsS2gFuOA=,iv:2sp9rK7uKxhY3qg4tpDa0heEYOUQziL/uwuvg41LMMA=,tag:vRfq+8++qfmbfBUl4snh8g==,type:str]
    version: 3.13.1
